### ISSUE TITLE
Add email notifications for devices

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-api#117]
Using the built-in mailer and sidekiq create notifications for:

1. **Device battery is low:** When the battery is below 15% send a notification. To avoid sending duplicate emails we might need to ass a flag that resets once the battery is greater than 15%, Also a 24h min interval between emails can be used.

2. **Device stop publishing:** When a device stops publishing for a definable period send a notification. That means all the devices `published_at` property needs to be evaluated every 1-5 minutes. To avoid sending duplicate emails we might need to add a flag that resets once the device published again.

**Comment by viktorsmari** [comment]
Can be implemented as a daily check with #119

**Comment by viktorsmari** [comment]
### Ideas

We can have notifications **per device**. A user with 3 kits can decide to make only 1 device give him email warnings.

If every device would have the attributes::
* notify_low_battery
* notify_stopped_publishing

**Comment by viktorsmari** [comment]
## Requirements
1. A user with 3 kits can decide to make only 1 device give him email warnings.
2. We want to have notifications **per device**. 
3. He only wants to get notified when a device stops publishing, not when the battery is low (or vice versa).

## TODO:
- [ ] How often should we check for `stopped_publishing`?
- [ ] How often should we check for `low_battery`?
- [ ] Front End: Where the user controls if to get notified for these purposes.

### How to prevent getting multiple emails per day?
1. The API checks only once per day.
   * Pros: Simple. No need to save a timestamp.
   * Cons: Maybe the user wants the email as soon as the device turns off / stops publishing. Not 23 hours later.
1. The API saves the timestamp when the last email was sent.
   * Before sending emails, check if `device.notify_low_battery_timestamp < 1.day.ago`

### Battery low
* 10.00 Battery goes below 15% 
* 10.30 `CheckBatteryLevelBelow` runs and sends an email
* 11.00 Battery goes to 20
* 12.00 Battery goes below 15% again
* 12.30 `CheckBatteryLevelBelow` and `notify_low_battery_timestamp` is 10.30
* We only send emails if 1 day has passed since last email?
 
### Stopped publishing
* 10.00 Device stops publishing   and `notify_stopped_publishing` is `true`
* 10.30 `CheckDeviceStoppedPublishing` runs and sends an email
* 11.00 Device starts publishing again
* 12.00 Device stops publishing again
* 12.30 `CheckDeviceStoppedPublishing` runs again and `notify_stopped_publishing_timestamp` is 10.30 (when the last email was sent)
* We only send emails if 12.hours has passed since last email was sent.

### Migration
The timestamps need to have a **default: date** so they won't fail the comparison 
`notify_stopped_publishing_timestamp`

Example Device after the change:
``` 
 notify_stopped_publishing_timestamp: Wed, 16 Jan 2019 16:19:35 UTC +00:00,
 notify_low_battery_timestamp: Wed, 16 Jan 2019 16:19:35 UTC +00:00,
 notify_low_battery: false,
 notify_stopped_publishing: false
```
